apiVersion: apiconnect.ibm.com/v1beta1
kind: APIConnectCluster
metadata:
  name: apic-single-cluster-production
  labels:
    app.kubernetes.io/instance: apiconnect
    app.kubernetes.io/managed-by: ibm-apiconnect
    app.kubernetes.io/name: apic-single-cluster-production
spec:
  license:
    accept: true
    use: production
    license: L-RJON-BZEP9N
  analytics:
    storage:
      enabled: true
      type: unique
  storageClassName: ibmc-vpc-block-metro-10iops-tier
  profile: n3xc14.m48
  version: 10.0.3.0